version: "3.5"

networks:
  kafka:
    driver: overlay
    attachable: true

services:
  kafka-source:
    image: lozuwa/kafka:v2.5.0
    environment:
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_AUTO_DELETE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-source:2181"
      KAFKA_LISTENERS: PLAINTEXT_DOCKER://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_DOCKER://kafka-source:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      Z: "zookeeper-source:2181"
      K: "kafka-source:9092"
    networks:
      - kafka
    ports:
      - target: 29092
        published: 29092
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        order: stop-first
        monitor: 25000ms
      restart_policy:
        condition: on-failure
        max_attempts: 2

