version: "3.5"

networks:
  kafka:
    driver: overlay
    attachable: true

configs:
  target_mm2.properties:
    file: ./target_mm2.properties

services:
  target_mmv2:
    image: gimral/kafka:mm2-2.7
    configs:
      - source: target_mm2.properties 
        target: /opt/kafka/config/mm2.properties
    environment:
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
      TOPIC_REPLICATION_MAPS: "source_topic_1:target_topic_1,source_topic_2:target_topic_2"
    networks:
      - kafka
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        order: stop-first
        monitor: 25000ms
      restart_policy:
        condition: on-failure
        max_attempts: 20

